builders:
  crimson:
    import: "package:crimson/generator.dart"
    builder_factories: ["getCrimsonGenerator"]
    build_extensions: { ".dart": ["crimson.g.part"] }
    auto_apply: dependents
    build_to: cache
    required_inputs: [".freezed.dart"]
    applies_builders: ["source_gen|combining_builder"]
